"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_01)\
$os\
$username\
[](bg:color_02 fg:color_01)\
$directory\
[](fg:color_02 bg:color_03)\
$git_branch\
$git_status\
[](fg:color_03 bg:color_04)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_04 bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]

color_fg1 = "#ffffff"
color_fg0 = '#000000'
color_bg1 = '#353539'
color_bg3 = '#525252'
color_04 = '#E7D379'
color_03 = '#E7798D'
color_green = '#98971a'
color_01 = '#79E7D3'
color_purple = '#b16286'
color_red = '#cc241d'
color_02 = '#798DE7'



[os]
disabled = false
style = "bg:color_01 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_01 fg:color_fg0"
style_root = "bg:color_01 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_02"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_03"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_03)]($style)'

[git_status]
style = "bg:color_03"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_03)]($style)'

[nodejs]
symbol = ""
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[c]
symbol = " "
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[rust]
symbol = ""
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[golang]
symbol = ""
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[php]
symbol = ""
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[java]
symbol = ""
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[kotlin]
symbol = ""
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[haskell]
symbol = ""
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[python]
symbol = ""
style = "bg:color_04"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_04)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg1 bg:color_bg1)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_02)'
